//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employe_tab
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "please enter your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "please enter the correct job Designation")]
        public string Designation { get; set; }
        [Required(ErrorMessage = "please enter the correct Address")]
        public string Address { get; set; }
    }
}
